export const FETCH_WEATHER = 'FETCH_WEATHER'
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS'
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE'

export const FETCH_WEATHER_COOR = 'FETCH_WEATHER_COOR'
export const FETCH_WEATHER_SUCCESS_COOR = 'FETCH_WEATHER_SUCCESS_COOR'
export const FETCH_WEATHER_FAILURE_COOR = 'FETCH_WEATHER_FAILURE_COOR'